### ISSUE TITLE
What version of this could lead to -

### ISSUE THREAD

**Issue by same110521** [MMarius84/Dell_Optiplex_5040_SFF#1]
I want to install Big Sur11.6.2, but can not enter the boot interface, stuck in the running code interface, how do you set up the BIOS before installation? The model is the same, but the processor is the I3-6100, the core display is the same

**Comment by MMarius84** [comment]
Hi there,

I just followed the Dortania guide in terms of [BIOS Seetings](https://dortania.github.io/OpenCore-Install-Guide/config.plist/skylake.html#intel-bios-settings).

Nothing more than that.

You should be fine with the recommended settings from the guide. I still use them to this day.

In terms of the CPU, except for the power draw, Core frequency and Core count, you should be looking at the same experience.

Best of luck.

**Comment by same110521** [comment]
Thank you so much for your reply. What version of MacOS are you using now? I'll try again when I get back in the evening. How is this (MSR needs to be deactivated-Not available in BIOS nor is it addressible from the config.plist) set up?

**Comment by MMarius84** [comment]
_> Thank you so much for your reply. What version of MacOS are you using now? I'll try again when I get back in the evening._ 

Running Ventura 12.4, thinking of giving Sonoma a try on a spare SSD

_> How is this (MSR needs to be deactivated-Not available in BIOS nor is it addressible from the config.plist) set up?_

I needed to use a modified version of GRUB in order to change the individual values for the **CFG Lock, MSR and DVMT Allocation Size** 
I have used [this guide](https://elitemacx86.com/threads/how-to-unlock-dvmt-pre-allocated-on-laptops.313/) as reference for my system

Best of luck

**Comment by same110521** [comment]
Hello, thank you very much for your EFI file, before the card code is not unlocked BIOS CFGLOCK, Brand Machine motherboard more trouble, Last Night with the mirror with EFI files in the open core boot interface after the unlock CFG, replace your EFI file with a successful MacOS Big Sur11.6.6 core display with a perfect driver and network card. But the audio drive was not successful, Motherboard BIOS recognized the sound card model ALC3234, but Hackintool recognized as ALC255, tried to change the ID but failed, tonight to replace the solid-state hard drive to re-install the Mac, and improve the drive, there is no wake up, wake up and no video output, my other PC i7-7700-gtx1060 is basically perfect, because the graphics card can not install the more advanced version of it idle. I Am Chinese, love electronic products, but also happy to toss. I believe all this can be solved perfectly if we work hard.

**Comment by MMarius84** [comment]
_> Last Night with the mirror with EFI files in the open core boot interface after the unlock CFG, replace your EFI file with a successful MacOS Big Sur11.6.6 core display with a perfect driver and network card_
Glad to hear that it worked for you.

_ >But the audio drive was not successful, Motherboard BIOS recognized the sound card model ALC3234, but Hackintool recognized as ALC255, tried to change the ID but failed_
LayoutID might be different for your motherboard, could also be a different chip. Have a look at the [Audio Guide from Dortania](https://dortania.github.io/OpenCore-Post-Install/universal/audio.html#finding-your-layout-id), and give a try with different layouts

_> tonight to replace the solid-state hard drive to re-install the Mac, and improve the drive, _
SSDs will surely improve the speed of the system.

_> there is no wake up, wake up and no video output_
This is a know issue with SkyLake iGPUs and there is no current solution for this.
I have decided to take the bullet and get a LowProfile Single Slot AMD RX550 4GB (Lexa Core) which I have spoofed as a RX550/RX560 (Baffin Core) and get better perfomance.
Getting full acceleration and wake was resolved. 


Best of luck.

**Comment by MMarius84** [comment]
Will close this

**Comment by same110521** [comment]
Good friend, I'm causing you trouble. I'm sleeping and I have to wake up early in the morning

**Comment by same110521** [comment]
Good friend, I'm causing you trouble. I'm sleeping and I have to wake up early in the morning
